services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aideb-backend
    ports:
      - "5003:5003" # Memetakan port 5003 host VPS ke port 5003 container
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/model_storage:/app/model_storage
    environment:
      - PORT=5003
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      # Optimasi RAM di tingkat container
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
    deploy:
      resources:
        limits:
          memory: 1.5G # Batasi penggunaan RAM backend maksimal 1.5 GB
    restart: always

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     args:
  #       # Masukkan URL/IP VPS Anda pada port 5003 di sini
  #       - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5003}
  #   container_name: aideb-frontend
  #   ports:
  #     - "3001:3000" # Memetakan port 3001 host VPS ke port 3000 container
  #   environment:
  #     - PORT=3000
  #     - NODE_ENV=production
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 500M # Batasi penggunaan RAM frontend maksimal 500 MB
  #   restart: always
  #   depends_on:
  #     - backend
