services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: detuji-backend
    ports:
      - "5002:5002" # Memetakan port 5002 host VPS ke port 5002 container
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/model_storage:/app/model_storage
    environment:
      - PORT=5002
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Masukkan URL/IP VPS Anda pada port 5002 di sini (contoh: http://103.xxx.xx.xx:5002)
        # secara default, ia akan fallback ke localhost jika tidak diset saat build
        - NEXT_PUBLIC_API_URL=http://localhost:5002
    container_name: detuji-frontend
    ports:
      - "3001:3000" # Memetakan port 3001 host VPS ke port 3000 container
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
    depends_on:
      - backend
